runname: "test"
base_dir: "."

min_similarity: "0.8" # threshold to pre-filter blast hits by percentage identity

silva:
  download-path-seq: "file://data/silva_db/sub_silva_seq_RNA.fasta.gz"
  download-path-tax: "file://data/silva_db/taxmap_slv_ssu_ref_nr_138.2.txt.gz"

card:
  download-path: "file://data/card_db/card_seq.tar.bz2"

num_parts: 1 # number of chunks the fastqs are split into
max_threads: 4

similarity_search_mode: "fast" # Put here fast or extensive for search on only forward or both strands

seq_tech: "ONT" # Put here "Illumina" or "ONT"