runname: "test"
base_dir: "/local/work/adrian/ERMA"  # User should change this path

min_similarity: "0.8" # threshold to pre-filter blast hits by percentage identity

num_parts: 1 # number of chunks the fastqs are split into
max_threads: 4

similarity_search_mode: "fast" # Put here fast or extensive

seq_tech: "ONT" # Put here "Illumina" or "ONT"